name: Build and Release Python Static Binaries

on:
  push:
    branches:
      - main  # Trigger on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Python for ${{ matrix.arch }}
        run: |
          docker buildx build --platform linux/${{ matrix.arch }} -t python-builder-${{ matrix.arch }} .
          mkdir -p output/${{ matrix.arch }}
          docker run --rm -v $(pwd)/output/${{ matrix.arch }}:/output python-builder-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-static-${{ matrix.arch }}
          path: output/${{ matrix.arch }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
        with:
          tag_name: "latest"
          release_name: "Latest Build"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/python-static-x86_64/python-3.13.2-static-x86_64.tar.gz
          asset_name: python-3.13.2-static-x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/python-static-aarch64/python-3.13.2-static-aarch64.tar.gz
          asset_name: python-3.13.2-static-aarch64.tar.gz
          asset_content_type: application/gzip